# Generated by Django 4.1.1 on 2022-09-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricecard',
            name='pc_description',
            field=models.CharField(max_length=200, verbose_name='Описание'),
        ),
    ]
