# Generated by Django 4.1.1 on 2022-09-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_alter_pricecard_pc_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetable',
            name='pt_price',
            field=models.CharField(max_length=200, null=True, verbose_name='Старая цена'),
        ),
    ]
