# Generated by Django 4.1.1 on 2022-09-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0003_alter_pricetable_pt_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetable',
            name='pt_price',
            field=models.CharField(max_length=200, verbose_name='Старая цена'),
        ),
    ]
