# Generated by Django 4.1.1 on 2022-09-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0004_alter_pricetable_pt_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetable',
            name='pt_price',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Старая цена'),
        ),
    ]
